version: '2'
services:
  web:
    image: mhart/alpine-node-auto
    build: .
    command: ['npm', 'run', 'dev']
    working_dir: /src
    container_name: vuex
    ports:
      - '8080:8080'
    volumes:
      - '.:/src'
